appdeploy:
  domain: private-testnet.infernos.io
  root: "false"
  path: app1
  whitelistIP: "true"
  whitelistIPlist: "173.48.233.154/32,0.0.0.0/0"
  authentication: "false"
  secret: "user:$apr1$wRzQ30hZ$EAUtmbpk83sbzMw/NaQJj0"
  image:
    repository: nginx
    tag: latest
    directcommand: "true"
    command: "npm start --prefix /my-app/."
  service:
    type: ClusterIP
  externalaccess:
    enabled: true
args: ['--arg3', 'value3', '--arg2', 'value2']