apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "appdeploy.fullname" . }}
  labels:
    app: {{ template "appdeploy.name" . }}
    chart: {{ template "appdeploy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: appdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "appdeploy.name" . }}
      release: {{ .Release.Name }}
      component: appdeploy
  template:
    metadata:
      labels:
        app: {{ template "appdeploy.name" . }}
        release: {{ .Release.Name }}
        component: appdeploy
    spec:
      containers:
      - name: appdeploy
        image: {{ .Values.appdeploy.image.repository }}:{{ .Values.appdeploy.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        {{- if .Values.appdeploy.image.directcommand }}
        command: ["/bin/sh"]
        args: ["-c", {{ .Values.appdeploy.image.command }}]
        {{- else }}
        args: [{{ .Values.appdeploy.image.args }}]
        {{- end }}
